---
# Install python for Ansible
- name: "install python for Ansible."
  become: yes
  apt:
    name: python3
    state: present

# Install Node.js 13.x
- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt-get install -y nodejs

# Install npm
# - name: install npm
# shell: |
#   sudo apt install libssl1.0-dev -y
#  sudo apt install nodejs-dev -y
# sudo apt install node-gyp -y
# sudo apt-get install -y npm

# Install PM2
- name: "install PM2."
  become: yes
  npm:
    name: pm2
    global: yes
